apiVersion: v1
kind: Service
metadata:
  name: nginx-svc
  namespace: nginx-guni1192
spec:
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
  selector:
    app: nginx
  type: ClusterIP
